PREFIX math: <http://www.w3.org/2000/10/swap/math#>
PREFIX geo: <http://www.opengis.net/ont/geosparql#>
PREFIX geof: <http://www.opengis.net/def/function/geosparql/>
PREFIX uom: <http://www.opengis.net/def/uom/OGC/1.0/>
PREFIX ex: <http://example.org/>

SELECT ?restaurant ?name ?distance
FROM <http://example.org/geo-position>
WHERE {
  ex:Makerspace geo:hasGeometry ?MakerspaceGeom .
  ?MakerspaceGeom geo:asWKT ?makerspaceWKT .
  
  ?restaurant a ex:Restaurant ;
              ex:name ?name ;
              geo:hasGeometry ?restaurantGeom .
  ?restaurantGeom geo:asWKT ?wkt .
  
   BIND(geof:distance(?makerspaceWKT, ?wkt, uom:metre) as ?distance)  
}



 # FILTER(geof:distance(?makerspaceWKT, ?wkt, uom:metre) < 700)