# Convert relative positions to absolute positions

PREFIX bot: <https://w3id.org/bot#>
PREFIX spatial: <http://example.org/spatial#>
PREFIX inst: <http://example.org/instances#>

select ?s ?relX ?relY ?relZ (sum(?_absX) as ?absX) (sum(?_absY) as ?absY) (sum(?_absZ) as ?absZ)
FROM <http://example.org/relative-position>
where {
  ?s a bot:element ;
     spatial:hasX ?relX ;
     spatial:hasY ?relY ;
     spatial:hasZ ?relZ.
  ?s spatial:hasParent* ?sp.
  ?sp spatial:hasX ?_X .
  ?sp spatial:hasY ?_Y .
  ?sp spatial:hasZ ?_Z .

  BIND(?_X as ?_absX)
  BIND(?_Y as ?_absY)
  BIND(?_Z as ?_absZ)

}
group by ?s ?relX ?relY ?relZ


# With filter for position

PREFIX bot: <https://w3id.org/bot#>
PREFIX spatial: <http://example.org/spatial#>
PREFIX inst: <http://example.org/instances#>

SELECT ?s (sum(?_absX) as ?absX) (sum(?_absY) as ?absY) (sum(?_absZ) as ?absZ)
FROM <http://example.org/relative-position>
WHERE {
  ?s a bot:element ;
     spatial:hasX ?relX ;
     spatial:hasY ?relY ;
     spatial:hasZ ?relZ.
  ?s spatial:hasParent* ?sp.
  ?sp spatial:hasX ?_X .
  ?sp spatial:hasY ?_Y .
  ?sp spatial:hasZ ?_Z .

  BIND(?_X as ?_absX)
  BIND(?_Y as ?_absY)
  BIND(?_Z as ?_absZ)

}
GROUP BY ?s
HAVING(
    ?absX >= -0.5 && ?absX <= 1.5 &&
    ?absY >= -0.5 && ?absY <= 1.5 &&
    ?absZ >= -0.5 && ?absZ <= 1.5
)